// Edit business information, services, prices and team names here.
export const business = {
  name: 'V Spa', phone: '647-857-1226', tel: '+16478571226', email: 'vspa.help@gmail.com',
  address: '525 Eglinton Ave W, Second Floor', city: 'Toronto, ON M5N 1B1',
  hours: 'Daily, 10 AM – 9 PM', map: 'https://www.google.com/maps/search/?api=1&query=525+Eglinton+Ave+W+Toronto',
};
export const services = [
  {slug:'30-minute-focused-relief-massage',title:'Focused Relief',duration:'30 min',price:50,image:'/images/spa-still-life.png',alt:'Spa towels, massage oil and orchids in soft candlelight',description:'A focused massage for a little breathing room in your day.',details:'Choose the areas that need the most attention. A shorter session leaves time for focused work on your neck, shoulders or back, with pressure adjusted to your comfort.',features:['Focused neck, shoulder or back massage','Light to medium pressure, tailored to you','Warm towel finish']},
  {slug:'45-minute-signature-flow-massage',title:'Signature Flow',duration:'45 min',price:60,image:'/images/spa-still-life.png',alt:'Spa towels, massage oil and orchids in soft candlelight',description:'A balanced full-body massage with warm oil and unhurried care.',details:'Our signature session combines flowing massage with more focused attention where you need it. Let your attendant know your preferred pressure and any areas you would like to focus on.',features:['Full-body relaxation massage','A blend of flowing and focused techniques','Warm oil and a calming finish']},
  {slug:'60-minute-total-immersion-massage',title:'Total Immersion',duration:'60 min',price:80,image:'/images/spa-still-life.png',alt:'Spa towels, massage oil and orchids in soft candlelight',description:'More time to slow down, settle in, and leave feeling refreshed.',details:'A longer full-body session gives you time to unwind at your own pace. Discuss your preferences before your massage, including pressure, focus areas, and any finishing touches.',features:['An extended full-body massage','Time for shoulders, back, scalp and feet','Personalized pressure and pacing']},
];
export const addons = [
  {slug:'body-scrub',title:'Body Scrub',price:25,description:'Gentle exfoliation and warm towels for soft, refreshed skin.'},
  {slug:'facials',title:'Facial',price:30,description:'Cleansing, exfoliation, a soothing mask and hydration.'},
  {slug:'back-shaving',title:'Back Grooming',price:40,description:'Careful skin preparation, back shaving and soothing aftercare.'},
  {slug:'intimate-shaving',title:'Intimate Grooming',price:55,description:'Personal grooming with clear boundaries, careful preparation and skin aftercare.'},
  {slug:'full-body-shaving',title:'Full-Body Grooming',price:220,description:'A complete grooming session with skin preparation and aftercare. Confirm areas and appointment length when booking.'},
];
export const team = [
  {name:'Judy',specialty:'Facials & grooming'}, {name:'Mona',specialty:'Relaxation & Swedish massage'},
  {name:'Elizabeth',specialty:'Massage & bodywork'}, {name:'Ayasha',specialty:'Relaxation massage'},
  {name:'Bella',specialty:'Massage & spa care'}, {name:'Amira',specialty:'Massage & spa care'},
  {name:'Amy',specialty:'Massage & spa care'}, {name:'Nazima',specialty:'Swedish massage & facials'},
];
export const guides = [
  {slug:'choosing-massage-toronto',title:'Find your ideal massage',summary:'A little guidance on time, pressure, and your first visit.',sections:[['Choose your time','Try 30 minutes when you want to focus on one or two areas, 45 minutes for a balanced full-body session, or 60 minutes for a slower pace.'],['Talk about pressure','Tell your attendant what feels comfortable. You can ask for lighter pressure, a pause, or a change at any point.'],['Before you arrive','Confirm your appointment, share any relevant sensitivities, and ask about products or fragrance-free options. Contact a qualified healthcare professional if you are unsure whether massage is appropriate for you.']]},
  {slug:'massage-addons-toronto',title:'The finishing touches',summary:'Explore body scrubs, facials, and personal grooming.',sections:[['Body scrubs','Gentle exfoliation can be added to a spa visit. Mention skin sensitivities and ask which products will be used.'],['Facials','A facial adds time for cleansing and hydration. Share allergies and preferences before treatment.'],['Grooming','Discuss the areas you want treated and the time required. The team will confirm pricing and clear service boundaries before your appointment.']]},
  {slug:'midtown-toronto-massage-spa-guide',title:'Your Midtown spa visit',summary:'Directions, appointment planning, and what to expect.',sections:[['Find us on Eglinton','V Spa is at 525 Eglinton Ave W, on the second floor. Check the contact page for directions and call if you need help finding the entrance.'],['Reserve ahead','Call or text with your preferred day, time, and massage length. Your appointment is confirmed only when the team replies.'],['Make yourself comfortable','Let us know your pressure, music, fragrance, and lighting preferences. Ask any questions before your session begins.']]},
  {slug:'evening-massage-toronto-after-work',title:'Make space after work',summary:'Plan a quiet pause at the end of your day.',sections:[['Evening appointments','The spa is open until 9 PM daily. Contact the team in advance to confirm the last available appointment for your chosen service.'],['Choose your session','A focused session can fit into a busy evening. A longer massage gives you more time to unwind.'],['Confirm before travelling','Same-day availability varies. Call or text before you set out so we can confirm the time and service.']]},
  {slug:'private-spa-rooms-toronto-gta',title:'A little room to unwind',summary:'A comfortable, private setting for your spa appointment.',sections:[['Your own space','Private treatment rooms help you settle into your appointment without distractions.'],['Your preferences','Ask about the room, products, and treatment before you book. Share any preferences for lighting, music, or fragrance.'],['Respectful care','Your comfort guides your visit. Communicate your boundaries and tell your attendant if you would like to change or stop a treatment.']]},
];
export const navigation=[['Home','/'],['Services','/services'],['Pricing','/pricing'],['Our team','/attendants'],['Appointments','/schedule'],['Experience','/experience'],['Contact','/contact']];
export const faq=[['Where is V Spa?','Find us at 525 Eglinton Ave W, Second Floor, in Midtown Toronto. We are open daily from 10 AM to 9 PM.'],['How do I book?','Call or text 647-857-1226 with your preferred day, time and service. Your appointment is confirmed when our team replies.'],['Can I add a facial or body scrub?','Yes. Mention any add-ons when you contact us so we can confirm the price and reserve enough time.'],['Are same-day visits available?','Availability changes throughout the day. Please call or text before travelling to the spa.']];

